### ISSUE TITLE
Add a key to the list item in MobileHeader.js

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#29]
## Problem or To-Do
Please add a key to the list item in `MobileHeader.js`. This should fix the following error:

```javascript
index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `MobileHeader`. See https://fb.me/react-warning-keys for more information.
    in li (at MobileHeader.js:35)
    in MobileHeader (at Header.js:17)
    in header (created by styled.header)
    in styled.header (at Header.js:19)
    in Header (at Layout.js:18)
    in div (created by styled.div)
    in styled.div (at Layout.js:17)
    in Layout (at src/index.js:51)
    in ApolloProvider (at src/index.js:50)
    in StrictMode (at src/index.js:49)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:48)
```

**Comment by minimatrix** [comment]
can I take this one please ?

**Comment by minimatrix** [comment]
Ok, so I think this issue is because the Logout component has been assigned a a key value which is also being applied to another list item, inside the map().
I've been unable to successfully authenticate so unfortunately I'm unable to test this, it's a very minor change.
Should I submit a PR for you to test? As I noticed another contributor was experiencing the same issue.
