### ISSUE TITLE
Write a hook to accept a parameter and return value for that key from url parameter

### ISSUE THREAD

**Issue by capndave** [capndave/gardenbuilder-frontend#3]
Please help write a hook to accept a parameter and return value for that key from url parameter. This will be useful in the `Garden` component, for example, so that we can grab a garden id from a param in the url, query the graphql server, and return info on a particular garden.

**Comment by heykc** [comment]
Hey @capndave I can work on this for hacktoberfest ✌️

**Comment by heykc** [comment]
Quick question. Since the `"/garden"` route is established in the index, is there any reason not to get the url param from the Route Props and pass that to the garden component, (or which ever component needs a parameter from url)?
<details>
<summary>example</summary>
<p>

```jsx
<Route path="/garden/:gardenId?/:someOtherParam?" render={(routerProps) => (
    // pass match.params into component as prop from routerProps
    <Garden urlParams={routerProps.match.params} />
  )} 
/>
```
</p>
</details>

<details>
<summary>then inside Garden component</summary>
<p>

```jsx
export function Garden(props) {
  // run query to graphQL
  // using gardenId param in urlParams from props
  const data = runSomeQuery(props.urlParams.gardenId);

  return (
    <div>
      <h2>{data.gardenName}</h2>
      {data.gardenInfo}
    </div>
  )
}
```
</p>
</details>

Otherwise, this hook would require you to pass in both the param name you want the value from, and the match property from routerProps. Apologies if I'm misunderstanding the issue. If I'm missing something, let me know where I'm off, and help me clarify what you're looking for. Thanks ~Keith

**Comment by capndave** [comment]
Keith - you're absolutely right. Perhaps this issue is moot

**Comment by capndave** [comment]
@heykc one can definitely pass this as a parameter in this case, but when routed to the Garden component the garden id will also be a part of the URL. I'd rather pull the parameter from the URL than as a passed property, partly because using this strategy we won't need to store the garden id of the selected garden (from the Gardens component) in state anywhere.

I'd like to do this in several components, actually, so it would be good to have a hook or a reusible function that accepts a url parameter name as an argument and returns the value associated with that key.

Did that answer your question? Let me know if not. I've reopened this issue.

**Comment by heykc** [comment]
Sorry that was my mistake for writing it out as if we needed to pass it through to our component manually. with React Router, those url parameters automatically are passed over to your rendered component by default. so in the index file you already have this:

```jsx
<Route path="/garden" component={Garden} />
```

now if you wanted to designate parameters, you would need to either assign required or optional param names in the path of this route like so

```jsx
<Route path="/garden/:gardenId" component={Garden} />
```

This way we aren't physically adding a prop to our Garden component and we can still access the garden ID by referencing `props.match.params.gardenId` anywhere in our Garden component. Otherwise, without using React Router's built in access to the URL, I'm not sure how to break up the URL by param name. Even if we grabbed the url by calling `window.location.pathname` and splitting the string at every "/" character, there's still no way to define them by name as they will just be an array of values.

Actually, can I get an example of what a URL might look like? Would the garden ID be a query param like so:
`http://example.com/garden?id=12345`
or would it look more like a subdirectory of garden like so:
`http://example.com/garden/12345`
If it's the former than I've been sorely mistaken this whole time and we can definitely use a hook to handle breaking up the params without the use of react router lol

Let me know, thanks!

**Comment by capndave** [comment]
It will look like `http://example.com/garden?id=12345`. I thought it was already in that format, actually, but I am mistaken! I'll update the url assignment in `Garden.js` to ensure that structure.

**Comment by capndave** [comment]
Ok it's updated.

**Comment by capndave** [comment]
Ok I wasn't really aware that React Router injected properties like that. If pulling the `id` parameter is that simple, I guess we don't need a dedicated hook/function'

**Comment by heykc** [comment]
Not entirely true, if you are planning on having the ids come from a search param like you mentioned i.e. `http://example.com/garden?id=12345` we would still have to parse the url via our own made parser or using a package like query-string. In that case, a hook would be a little cleaner to understand rather than knowing when to import the query-string if we need it. 

an example of the hook

```js
import qString from 'query-string';

const useUrlParam = (paramName) => {
  const params = qString.parse(location.search);
  return params[paramName] || null;
}

export {useUrlParam};
```

and in use: 
```jsx
import useUrlParam from './path/to/useUrlParam';

export function Garden(props) {
  // run query to graphQL
  // using gardenId param in urlParams from props
  const data = runSomeQuery(useUrlParam('gardenId'));

  return (
    <div>
      <h2>{data.gardenName}</h2>
      {data.gardenInfo}
    </div>
  )
}
```

using the hook like so would be more declarative for the components rather than parsing the search params manually for every component you want to use it in.

**Comment by capndave** [comment]
Great, want to bust that out?
